version: '3.7'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 01factory
      MYSQL_USER: 01factory
      MYSQL_PASSWORD: 01factory
      MYSQL_ROOT_PASSWORD: 01factory
    ports:
      - 3306:3306

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: 01factory
      POSTGRES_USER: 01factory
      POSTGRES_PASSWORD: 01factory
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: 01factory
      MINIO_SECRET_KEY: 01factory
